openapi: 3.0.0
info:
  title: Wedding Pro API
  description: API for Wedding Pro application
  version: 1.0.0
  contact:
    name: Wedding Pro Team
    email: support@weddingpro.com
    url: https://weddingpro.com/support
servers:
  - url: https://api.weddingpro.com/v1
    description: Production server
  - url: http://localhost:3000/api
    description: Local development server
tags:
  - name: Authentication
    description: Authentication related endpoints
paths:
  /auth/login:
    post:
      operationId: loginUser
      tags:
        - Authentication
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
      summary: User login
      description: Authenticates a user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
components:
  parameters:
    CorrelationId:
      name: X-Correlation-ID
      in: header
      description: Correlation ID for request tracing
      schema:
        type: string
        format: uuid
      required: false
  schemas:
    User:
      type: object
      description: User information
      required:
        - id
        - email
      properties:
        id:
          type: string
          format: uuid
          description: Unique user identifier
        email:
          type: string
          format: email
          description: User's email address
        name:
          type: string
          description: User's full name
        role:
          type: string
          enum: [user, admin]
          description: User's role in the system